### ISSUE TITLE
Rollback to savepoint throws TransactionRequiredException

### ISSUE THREAD

**Issue by harture** [cockroachdb/hibernate-savepoint-fix#1]
Hello,

I am building a minimal exemple with Hibernate & CockroachDB.
My objective is to test the client side retry with SAVEPOINT (code avaialable at https://github.com/cloudtrust/examples-orms/blob/savepoint/java/hibernate), to do so I did a concurrencyTest to reach this scenario. 
When it tries to rollback to savepoint, it throws `javax.persistence.TransactionRequiredException: Executing an update/delete query` although I am using your hibernate-savepoint-fix.

The issue seems due to the TransactionCoordinator.isActive() method which return false as the connection is neither ACTIVE nor MARKED_ROLLBACK. 
Overriding this method to also returns true for FAILED_COMMIT and ROLLED_BACK statuses leads to `org.postgresql.util.PSQLException: ERROR: SAVEPOINT COCKROACH_RESTART has not been used`.

Am I using your fix incorrectly or is it a bug ?

Cheers

**Comment by harture** [comment]
Hello,

Is there any news about this issue and can I do something to help you ? 
Do you think we could find a way to work together to fix it ?

Cheers

**Comment by justinj** [comment]
Hi @harture,

Happy to look into this with you! I'm a little paged out on the details here so if you have any interest in investigating how this could be fixed that would be much appreciated! Happy to help you out in any way I can if that's a path you're interested in going down.

**Comment by harture** [comment]
Hi @justinj,

Actually I discovered that I was using things wrong. In my test case, I was doing a `tx.commit()` instead of `RELEASE SAVEPOINT`. 
With the correct operation it works fine 😊
My bad, sorry for the inconvenience.

**Comment by justinj** [comment]
That's great to hear! No worries at all :)
